let main = document.createElement("div");
main.setAttribute("id", "main");
const body = document.querySelector("body");
body.appendChild(main);
let img = document.createElement("img");
img.src = "/images/brain dudey.jpg";
main.appendChild(img);
let div1 = document.createElement("div");
div1.setAttribute("id", "heading");
body.appendChild(div1);
let h1a = document.createElement("h1");
h1a.setAttribute("id", "topic");
h1a.innerHTML = "BRAIN DUDEY";
div1.appendChild(h1a);
let br = document.createElement("br");
body.appendChild(br);
let div2 = document.createElement("div");
div2.setAttribute("id", "headinggap");
let span = document.createElement("span");
div2.appendChild(span);
body.append(div2);
let div3 = document.createElement("div");
div3.setAttribute("id", "address");
let p1 = document.createElement("p");
p1.innerText =
  "N.Damen Avenue,Chicago 99999|999-999-9999|hello@kickresume.com|www.kickresume.com";
div3.append(p1);
body.append(div3);
let hr = document.createElement("hr");
body.append(hr);
let div4 = document.createElement("div");
div4.setAttribute("class", "leftside");
let div5 = document.createElement("div");
div5.setAttribute("id", "profiles");
let i1 = document.createElement("i");
i1.setAttribute("id", "profile");
i1.innerHTML = "<i class='fa fa-user' aria-hidden='true'></i>";
div5.append(i1);
let h1b = document.createElement("h1");
h1b.setAttribute("id", "profilechar");
h1b.innerHTML = "Profile";
div5.append(h1b);
let p2 = document.createElement("p");
p2.setAttribute("id", "paraprofile");
p2.innerHTML =
  "innovation optimized solution seeker.Excited to be<br>at the deployment phase of my new career as a<br>web developer. I am ambitious, adventurous,<br>assiduous,animated,and an alliteration advocate.</p>";
div5.appendChild(p2);
div4.append(div5);
let div6 = document.createElement("div");
div6.setAttribute("id", "skill");
let i2 = document.createElement("i");
i2.innerHTML = "<i class='fa fa-flask' aria-hidden='true'></i>";
i2.setAttribute("id", "flask");
div6.append(i2);
let p3 = document.createElement("p");
p3.setAttribute("id", "skillheading");
p3.innerHTML = "Skills";
div6.append(p3);
let p4 = document.createElement("p");
p4.innerHTML = "<strong>Technical Skills</strong>";
p4.setAttribute("id", "technicalskills");
div6.append(p4);
let table1 = document.createElement("table");
table1.setAttribute("id", "table1");
let thead1 = document.createElement("thead");
let tbody1 = document.createElement("tbody");
div6.append(table1);
div6.append(thead1);
div6.append(tbody1);
let row1 = document.createElement("tr");
let row1data1 = document.createElement("td");
row1data1.innerHTML = "JavaScript";
let row1data2 = document.createElement("td");
row1data2.innerHTML =
  "<input type='range'  min='1' max='100' value='80' disabled>";
div6.append(row1);
div6.append(row1data1);
div6.append(row1data2);
let row2 = document.createElement("tr");
let row2data1 = document.createElement("td");
row2data1.innerHTML = "CSS";
let row2data2 = document.createElement("td");
row2data2.innerHTML =
  "<input type='range'  min='1' max='100' value='80' disabled>";
div6.append(row2);
div6.append(row2data1);
div6.append(row2data2);
let row3 = document.createElement("tr");
let row3data1 = document.createElement("td");
row3data1.innerHTML = "HTML";
let row3data2 = document.createElement("td");
row3data2.innerHTML =
  "<input type='range'  min='1' max='100' value='50' disabled>";
div6.append(row3);
div6.append(row3data1);
div6.append(row3data2);
let row4 = document.createElement("tr");
let row4data1 = document.createElement("td");
row4data1.innerHTML = "React";
let row4data2 = document.createElement("td");
row4data2.innerHTML =
  "<input type='range'  min='1' max='100' value='50' disabled>";
div6.append(row4);
div6.append(row4data1);
div6.append(row4data2);
let row5 = document.createElement("tr");
let row5data1 = document.createElement("td");
row5data1.innerHTML = "Redux";
let row5data2 = document.createElement("td");
row5data2.innerHTML =
  "<input type='range'  min='1' max='100' value='80' disabled>";
div6.append(row5);
div6.append(row5data1);
div6.append(row5data2);
let row6 = document.createElement("tr");
let row6data1 = document.createElement("td");
row6data1.innerHTML = "Mongo";
let row6data2 = document.createElement("td");
row6data2.innerHTML =
  "<input type='range'  min='1' max='100' value='80' disabled>";
div6.append(row6);
div6.append(row6data1);
div6.append(row6data2);
let row7 = document.createElement("tr");
let row7data1 = document.createElement("td");
row7data1.innerHTML = "Deployment";
let row7data2 = document.createElement("td");
row7data2.innerHTML =
  "<input type='range'  min='1' max='100' value='100' disabled>";
div6.append(row7);
div6.append(row7data1);
div6.append(row7data2);
let p5 = document.createElement("p");
p5.innerHTML = "<strong>Additional Skills</strong>";
p5.setAttribute("id", "additional");
div6.append(p5);
let table2 = document.createElement("table");
let thead2 = document.createElement("thead");
let tbody2 = document.createElement("tbody");
div6.append(table2);
div6.append(thead2);
div6.append(tbody2);
let row1a = document.createElement("tr");
let row1adata1 = document.createElement("td");
row1adata1.innerHTML = "Project Management";
let row1adata2 = document.createElement("td");
row1adata2.innerHTML =
  "<input type='range'  min='1' max='100' value='100' disabled>";
div6.append(row1a);
div6.append(row1adata1);
div6.append(row1adata2);
let row1b = document.createElement("tr");
let row1bdata1 = document.createElement("td");
row1bdata1.innerHTML = "Recruitment";
let row1bdata2 = document.createElement("td");
row1bdata2.innerHTML =
  "<input type='range'  min='1' max='100' value='80' disabled>";
div6.append(row1b);
div6.append(row1bdata1);
div6.append(row1bdata2);
let row1c = document.createElement("tr");
let row1cdata1 = document.createElement("td");
row1cdata1.innerHTML = "Business Development";
let row1cdata2 = document.createElement("td");
row1cdata2.innerHTML =
  "<input type='range'  min='1' max='100' value='100' disabled>";
div6.append(row1c);
div6.append(row1cdata1);
div6.append(row1cdata2);
let row1d = document.createElement("tr");
let row1ddata1 = document.createElement("td");
row1ddata1.innerHTML = "Editing";
let row1ddata2 = document.createElement("td");
row1ddata2.innerHTML =
  "<input type='range'  min='1' max='100' value='80' disabled>";
div6.append(row1d);
div6.append(row1ddata1);
div6.append(row1ddata2);
let row1e = document.createElement("tr");
let row1edata1 = document.createElement("td");
row1edata1.innerHTML = "Fundrasing";
let row1edata2 = document.createElement("td");
row1edata2.innerHTML =
  "<input type='range'  min='1' max='100' value='100' disabled>";
div6.append(row1e);
div6.append(row1edata1);
div6.append(row1edata2);
div4.append(div6);
let div7 = document.createElement("div");
div7.setAttribute("id", "workexperience");
let i3 = document.createElement("i");
i3.setAttribute("id", "work");
i3.innerHTML = "<i class='fa fa-briefcase' aria-hidden='true'></i>";
div7.append(i3);
let p6 = document.createElement("p");
p6.innerHTML = "Work Experience";
p6.setAttribute("id", "works");
div7.append(p6);
let p7 = document.createElement("p");
p7.innerHTML =
  "<strong>Event Manager</strong> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 03/2014-02/2017<br>C3 Presents,WashingtonDC";
div7.append(p7);
let ul1 = document.createElement("ul");
div7.append(ul1);
let li1 = document.createElement("li");
li1.innerHTML =
  "Lead and execute all phases of event planning<br>and &emsp; production &emsp; spanning &emsp; committee<br>recruitment,training,vendor relationships and<br>on-site facilitation.";
div7.append(li1);
let li2 = document.createElement("li");
li2.innerHTML =
  "Brought new business to the organization<br>through relentless networking and stewardship<br>which helped the company win the bid for the<br>State Department largest civis event to date,the<br>United State of Women.";
div7.append(li2);
let li3 = document.createElement("li");
li3.innerHTML =
  "Exercise fiscal control over budget creation,<br>tracking&emsp;and&emsp;reporting.&emsp;Collaborate&emsp;with<br>employees&emsp;at&emsp;all&emsp;organization&emsp;levels&emsp;to<br>advance cohesive operations.";
div7.append(li3);
div4.append(div7);
body.append(div4);
let div8 = document.createElement("div");
div8.setAttribute("id", "rightside");
let div9 = document.createElement("div");
div9.setAttribute("id", "workexperience2");
let i4 = document.createElement("i");
i4.setAttribute("id", "work2");
i4.innerHTML = "<i class='fa fa-briefcase' aria-hidden='true'></i>";
div9.append(i4);
let p8 = document.createElement("p");
p8.setAttribute("id", "wexp");
p8.innerHTML = "Work Experience";
div9.append(p8);
let p9 = document.createElement("p");
p9.setAttribute("id", "workpara2");
p9.innerHTML =
  "<strong>Community Relation</strong> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 06/2011 - 01/2014<br><strong>Manager</strong><br>Gay & Lesbian Elder Housing,Los Angeles";
div9.append(p9);
let ul2 = document.createElement("ul");
ul2.setAttribute("id", "community");
div9.append(ul2);
let lia = document.createElement("li");
lia.innerHTML = "Arranging presentations and pitch deck.";
div9.append(lia);
let lib = document.createElement("li");
lib.innerHTML =
  "Designing a PR plan and establishing<br>important focus points.";
div9.append(lib);
let lic = document.createElement("li");
lic.innerHTML =
  "Designing,creating and managing content<br>cross multiple communication platforms.";
div9.append(lic);
let lid = document.createElement("li");
lid.innerHTML = "Buliding relationships with key media players.";
div9.append(lid);
div8.append(div9);
let div10 = document.createElement("div");
div8.append(div10);
div10.setAttribute("id", "education");
let i5 = document.createElement("i");
i5.innerHTML = "<i class='fa fa-graduation-cap' aria-hidden='true'></i>";
i5.setAttribute("id", "graduation");
div10.append(i5);
let p10 = document.createElement("p");
p10.innerHTML = "Education";
p10.setAttribute("id", "edu");
div10.append(p10);
let p11 = document.createElement("p");
p11.setAttribute("id", "workpara2");
p11.innerHTML =
  "<strong>Engineering Immersion</strong> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 11/2018 - 06/2018<br><strong>Program</strong><br>Thinking,Chicago,IL";
div10.append(p11);
let p12 = document.createElement("p");
p12.innerHTML =
  "Project-focused intensive program with emphasis<br>on Mongo,Express,React,and JavaScripit (MERN)<br>technical stack.";
div10.append(p12);
let ulA = document.createElement("ul");
div10.append(ulA);
let liA = document.createElement("li");
liA.innerHTML =
  "Developed a full-stack web application,<br>'RenewU',using React that allows users to<br>explore various aspects of meditation.User's<br>progress is stored on a backend created using<br>Node and MongoDB.";
div10.append(liA);
let liB = document.createElement("li");
liB.innerHTML =
  "Developed a language learning app. 'Foodie<br>Phonetics' using spaced repetition and a linked<br>list data structure. React was used to create<br>the front end components while Node and<br>Mongo were used to create a backend that><br>stores user data.";
div10.append(liB);
let liC = document.createElement("li");
liC.innerHTML =
  "Developed a concierge app. 'Pley', for<br>individuals looking for curated suggestions<br>when visiting a new place. React was used to<br>develop the front end which includes real-time<br>chat, drag and drop and variety of advanced<br>features. The backend, built using Node,<br>Express, and Mongo, takes advantage of well-<br>developed RESTful API, Geospatial searching,<br>and user authentication with JWT.";
div10.append(liC);
let p13 = document.createElement("p");
p13.innerHTML =
  "<strong>BA,English</strong> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 09/2001-2005<br>University of Calfornia,Los Angles";
div10.append(p13);
body.append(div8);
